import React,{useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const demo=[
 {id:1,name:'Rahul Sharma',company:'ABC Realty',service:'Performance Ads',industry:'Real Estate',budget:'₹50,000/month',timeline:'2 weeks',score:92,priority:'HOT',status:'New',source:'Website',email:'rahul@example.com',message:'Need more qualified property leads.'},
 {id:2,name:'Amit Verma',company:'UrbanFit',service:'Website + CRO',industry:'Fitness',budget:'₹30,000',timeline:'1 month',score:76,priority:'WARM',status:'Contacted',source:'WhatsApp',email:'amit@example.com',message:'Need a new conversion-focused website.'},
 {id:3,name:'Priya Singh',company:'Glow Studio',service:'SEO',industry:'Beauty',budget:'Unknown',timeline:'3 months',score:43,priority:'COLD',status:'Nurture',source:'Instagram',email:'priya@example.com',message:'Exploring SEO options.'}
];
function scoreLead(f){let s=0;if(f.service)s+=20;if(f.budget&&f.budget!=='Unknown')s+=25;if(f.timeline==='2 weeks')s+=30;else if(f.timeline==='1 month')s+=20;else if(f.timeline==='3 months')s+=10;if(f.company)s+=10;if(f.message?.length>20)s+=7;return Math.min(100,s)}
function App(){const [leads,setLeads]=useState(demo);const [view,setView]=useState('dashboard');const [selected,setSelected]=useState(null);const [form,setForm]=useState({});const stats=useMemo(()=>({total:leads.length,hot:leads.filter(x=>x.priority==='HOT').length,warm:leads.filter(x=>x.priority==='WARM').length,meetings:leads.filter(x=>x.status==='Meeting Booked').length}),[leads]);
 const submit=e=>{e.preventDefault();const score=scoreLead(form);const priority=score>=80?'HOT':score>=55?'WARM':'COLD';const lead={...form,id:Date.now(),score,priority,status:'New',source:'Demo Form'};setLeads([lead,...leads]);setForm({});setView('dashboard')};
 return <div className="app"><header><div><span className="eyebrow">DIGITAL WHOPPER • AUTOMATION DEMO</span><h1>LeadFlow <span>Automation</span></h1></div><nav><button onClick={()=>setView('dashboard')} className={view==='dashboard'?'active':''}>Dashboard</button><button onClick={()=>setView('intake')} className={view==='intake'?'active':''}>Test Lead Form</button></nav></header>
 {view==='intake'?<main className="center"><section className="card formcard"><h2>Submit a new enquiry</h2><p>Test the lead-to-sales automation flow.</p><form onSubmit={submit}>{[['name','Full name'],['company','Company'],['email','Email'],['industry','Industry'],['service','Required service'],['budget','Budget']].map(([k,l])=><input key={k} required={['name','company','email','service'].includes(k)} placeholder={l} value={form[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})}/>)}<select value={form.timeline||''} onChange={e=>setForm({...form,timeline:e.target.value})}><option value="">Timeline</option><option>2 weeks</option><option>1 month</option><option>3 months</option></select><textarea placeholder="Requirement" value={form.message||''} onChange={e=>setForm({...form,message:e.target.value})}/><button className="primary">Run Automation →</button></form></section></main>:<main><div className="stats"><div><b>{stats.total}</b><span>Total Leads</span></div><div><b>{stats.hot}</b><span>🔥 Hot Leads</span></div><div><b>{stats.warm}</b><span>Warm Leads</span></div><div><b>{stats.meetings}</b><span>Meetings</span></div></div><div className="grid"><section className="card"><div className="sectionhead"><div><h2>Lead pipeline</h2><p>Every enquiry is automatically scored and routed.</p></div><button className="primary small" onClick={()=>setView('intake')}>+ Test Lead</button></div><div className="table"><div className="tr head"><span>Lead</span><span>Service</span><span>Score</span><span>Status</span></div>{leads.map(l=><div className="tr" key={l.id} onClick={()=>setSelected(l)}><span><b>{l.name}</b><small>{l.company} · {l.source}</small></span><span>{l.service}</span><span><strong className={l.priority.toLowerCase()}>{l.score}</strong></span><span><em className={l.priority.toLowerCase()}>{l.priority}</em> {l.status}</span></div>)}</div></section><aside className="card flow"><h2>Automation flow</h2>{['Lead received','Lead scored','CRM updated','Sales notification','Meeting booking','Follow-up sequence'].map((x,i)=><div className="step" key={x}><i>{i+1}</i><span>{x}</span><b>✓</b></div>)}<div className="notice">Demo mode — connect Supabase, WhatsApp, email and calendar after validation.</div></aside></div></main>}
 {selected&&<div className="overlay" onClick={()=>setSelected(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><span className={'pill '+selected.priority.toLowerCase()}>{selected.priority} · {selected.score}/100</span><h2>{selected.name}</h2><p>{selected.company} · {selected.industry}</p><hr/><div className="details"><b>Service</b><span>{selected.service}</span><b>Budget</b><span>{selected.budget||'Unknown'}</span><b>Timeline</b><span>{selected.timeline||'Unknown'}</span><b>Source</b><span>{selected.source}</span><b>Email</b><span>{selected.email}</span></div><button className="primary full">Book meeting →</button></div></div>}</div>}
createRoot(document.getElementById('root')).render(<App/>);
