import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';
import {supabase} from './supabase';

const demo=[
 {id:'demo-1',name:'Rahul Sharma',company:'ABC Realty',service:'Performance Ads',industry:'Real Estate',budget:'₹50,000/month',timeline:'2 weeks',score:92,priority:'HOT',status:'New',source:'Website',email:'rahul@example.com',message:'Need more qualified property leads.'},
 {id:'demo-2',name:'Amit Verma',company:'UrbanFit',service:'Website + CRO',industry:'Fitness',budget:'₹30,000',timeline:'1 month',score:76,priority:'WARM',status:'Contacted',source:'WhatsApp',email:'amit@example.com',message:'Need a new conversion-focused website.'},
 {id:'demo-3',name:'Priya Singh',company:'Glow Studio',service:'SEO',industry:'Beauty',budget:'Unknown',timeline:'3 months',score:43,priority:'COLD',status:'Nurture',source:'Instagram',email:'priya@example.com',message:'Exploring SEO options.'}
];
function scoreLead(f){let s=0;if(f.service)s+=20;if(f.budget&&f.budget!=='Unknown')s+=25;if(f.timeline==='2 weeks')s+=30;else if(f.timeline==='1 month')s+=20;else if(f.timeline==='3 months')s+=10;if(f.company)s+=10;if((f.message||'').length>20)s+=7;return Math.min(100,s)}
function normalizeLead(l){return {...l,score:l.lead_score??0,priority:(l.priority||'cold').toUpperCase(),status:(l.status||'new').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase()),message:l.summary||''}}
function App(){const [leads,setLeads]=useState([]);const [view,setView]=useState('dashboard');const [selected,setSelected]=useState(null);const [form,setForm]=useState({});const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');
 const load=async()=>{setLoading(true);const {data,error}=await supabase.from('leads').select('*').order('created_at',{ascending:false});if(error){setError(error.message);setLeads(demo)}else setLeads(data?.length?data.map(normalizeLead):demo);setLoading(false)};useEffect(()=>{load()},[]);
 const stats=useMemo(()=>({total:leads.length,hot:leads.filter(x=>x.priority==='HOT').length,warm:leads.filter(x=>x.priority==='WARM').length,meetings:leads.filter(x=>x.status==='Meeting Booked').length}),[leads]);
 const submit=async e=>{e.preventDefault();setSaving(true);setError('');const score=scoreLead(form);const priority=score>=80?'hot':score>=55?'warm':'cold';const payload={name:form.name,company:form.company,email:form.email,phone:form.phone||null,industry:form.industry||null,service:form.service,budget:form.budget||null,timeline:form.timeline||null,source:'Demo form',lead_score:score,priority,summary:form.message||null,status:'new'};const {data,error}=await supabase.from('leads').insert(payload).select().single();if(error){setError(error.message)}else{setLeads(x=>[normalizeLead(data),...x]);setForm({});setView('dashboard')}setSaving(false)};
 return <div className="app"><header><div><span className="eyebrow">DIGITAL WHOPPER • AUTOMATION DEMO</span><h1>LeadFlow <span>Automation</span></h1></div><nav><button onClick={()=>setView('dashboard')} className={view==='dashboard'?'active':''}>Dashboard</button><button onClick={()=>setView('intake')} className={view==='intake'?'active':''}>Test Lead Form</button></nav></header>
 {error&&<div className="error">{error}</div>}
 {view==='intake'?<main className="center"><section className="card formcard"><h2>Submit a new enquiry</h2><p>Submission is saved directly to Supabase.</p><form onSubmit={submit}>{[['name','Full name'],['company','Company'],['email','Email'],['phone','Phone'],['industry','Industry'],['service','Required service'],['budget','Budget']].map(([k,l])=><input key={k} required={['name','company','email','service'].includes(k)} placeholder={l} value={form[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})}/>)}<select value={form.timeline||''} onChange={e=>setForm({...form,timeline:e.target.value})}><option value="">Timeline</option><option>2 weeks</option><option>1 month</option><option>3 months</option></select><textarea placeholder="Requirement" value={form.message||''} onChange={e=>setForm({...form,message:e.target.value})}/><button disabled={saving} className="primary">{saving?'Saving…':'Run Automation →'}</button></form></section></main>:<main><div className="stats"><div><b>{stats.total}</b><span>Total Leads</span></div><div><b>{stats.hot}</b><span>🔥 Hot Leads</span></div><div><b>{stats.warm}</b><span>Warm Leads</span></div><div><b>{stats.meetings}</b><span>Meetings</span></div></div><div className="grid"><section className="card"><div className="sectionhead"><div><h2>Lead pipeline</h2><p>{loading?'Loading from Supabase…':'Every enquiry is scored and stored in Supabase.'}</p></div><button className="primary small" onClick={()=>setView('intake')}>+ Test Lead</button></div><div className="table"><div className="tr head"><span>Lead</span><span>Service</span><span>Score</span><span>Status</span></div>{leads.map(l=><div className="tr" key={l.id} onClick={()=>setSelected(l)}><span><b>{l.name}</b><small>{l.company} · {l.source}</small></span><span>{l.service}</span><span><strong className={(l.priority||'cold').toLowerCase()}>{l.score}</strong></span><span><em className={(l.priority||'cold').toLowerCase()}>{l.priority}</em> {l.status}</span></div>)}</div></section><aside className="card flow"><h2>Automation flow</h2>{['Lead received','Lead scored','Supabase CRM updated','Sales notification','Meeting booking','Follow-up sequence'].map((x,i)=><div className="step" key={x}><i>{i+1}</i><span>{x}</span><b>✓</b></div>)}<div className="notice">Live database connected. WhatsApp, email and calendar can be added next.</div></aside></div></main>}
 {selected&&<div className="overlay" onClick={()=>setSelected(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><span className={'pill '+selected.priority.toLowerCase()}>{selected.priority} · {selected.score}/100</span><h2>{selected.name}</h2><p>{selected.company} · {selected.industry}</p><hr/><div className="details"><b>Service</b><span>{selected.service}</span><b>Budget</b><span>{selected.budget||'Unknown'}</span><b>Timeline</b><span>{selected.timeline||'Unknown'}</span><b>Source</b><span>{selected.source}</span><b>Email</b><span>{selected.email}</span></div><button className="primary full">Book meeting →</button></div></div>}</div>}
createRoot(document.getElementById('root')).render(<App/>);
